import Head from 'next/head';
import Footer from '../components/footer/footer';
import styles from '../styles/home.module.scss';
import Socials from "../sections/socials/socials";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}

      <main className={styles.main}>main</main>

      {/*  socials */}
        <Socials />

      {/* footer */}
      <Footer />
    </>
  );
}
